# 站点配置
title: Kieran 的个人主页
tagline: "医学 · 音乐 · 阅读 · 思考"
description: >-
  Kieran的个人空间。临床营养领域从业者，偶尔写写医学、音乐、阅读和思考。
url: "https://kiefeng.github.io"
baseurl: ""
github:
  username: kiefeng
social:
  name: Kieran
  email: yafc18992173463@gmail.com
  links:
    - https://github.com/kiefeng

# 主题
theme: jekyll-theme-chirpy

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# 语言
lang: zh-CN
timezone: Asia/Shanghai

# 头像
avatar: "https://avatars.githubusercontent.com/u/102287897?v=4"

# 外观
theme_mode: light
theme_color: blue

# 评论
comments:
  active: utterances
  utterances:
    repo: kiefeng/kiefeng.github.io
    issue_term: title

# 分页
paginate: 10

# 构建配置
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# 排除
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
